name = "tasktime-cors-proxy"
main = "src/index.js"
compatibility_date = "2024-09-23"

# TARGET se puede sobreescribir por entorno:
#   wrangler dev --var TARGET:https://otro/exec
#   wrangler deploy --var TARGET:https://otro/exec
[vars]
TARGET = "https://script.google.com/macros/s/AKfycbxsaSq9sEHFc9at2opoAVSyI1UboU7NsCU4VFEBAToAZ75NY_mjkWW38Y8_A-Q_BW7u/exec"

[dev]
port = 8787
