name = "finanzas-cors-proxy"
main = "src/index.js"
compatibility_date = "2024-09-23"

# TARGET se puede sobreescribir por entorno:
#   wrangler dev --var TARGET:https://otro/exec
#   wrangler deploy --var TARGET:https://otro/exec
[vars]
TARGET = "https://script.google.com/macros/s/AKfycbyPcNLcHbWFcZ4S3r9ld0HCsiox2_IsIlHWnyDr2VlPG3Ko6-wXrBCAmdoMd7VmG3Rk/exec"

[dev]
port = 8787