name = "finanzas-cors-proxy"
main = "src/index.js"
compatibility_date = "2024-09-23"

# TARGET se puede sobreescribir por entorno:
#   wrangler dev --var TARGET:https://otro/exec
#   wrangler deploy --var TARGET:https://otro/exec
[vars]
TARGET = "https://script.google.com/macros/s/AKfycbyT7IK7yvO0w7ys-w1zUf5PE1-ScRgywjHpjsNSSDNN6DkyNeQ_DfgzXRN9_h3sy2_Z/exec"

[dev]
port = 8787